name: jobs_pot
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/resources/i18n/langs/
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/icons/arrow/
    - lib/assets/icons/company/
    - lib/assets/icons/language/
    - lib/assets/icons/specialization/
    - lib/assets/icons/tabBar/
  fonts:
    - family: DMSans-Bold
      fonts:
        - asset: lib/resources/fonts/DMSans-Bold.ttf
    - family: DMSans-BoldItalic
      fonts:
        - asset: lib/resources/fonts/DMSans-BoldItalic.ttf
          style: italic
    - family: DMSans-Italic
      fonts:
        - asset: lib/resources/fonts/DMSans-Italic.ttf
          style: italic
    - family: DMSans-Medium
      fonts:
        - asset: lib/resources/fonts/DMSans-Medium.ttf
    - family: DMSans-MediumItalic
      fonts:
        - asset: lib/resources/fonts/DMSans-MediumItalic.ttf
          style: italic
    - family: DMSans-Regular
      fonts:
        - asset: lib/resources/fonts/DMSans-Regular.ttf