name: jobs_pot
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  #sub module
  logger:
    path: ../logger

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  flutter_svg: ^2.0.6
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  email_validator: ^2.1.17
  flutter_easyloading: ^3.0.5
  reactive_forms: ^16.1.1
  retrofit_generator: ^8.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.2.1
  shared_preferences: ^2.1.2
  flutter_riverpod: ^2.2.0
  auto_route: ^7.8.4
  fpdart: ^1.1.0
  crypto: ^3.0.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  http: ^1.1.0
  firebase_storage: ^11.2.5
  intl_phone_number_input: ^0.7.3+1
  dotted_border: ^2.0.0+3
  flutter_facebook_auth: ^6.0.2
  pinput: ^3.0.1
  fluttertoast: ^8.2.3
  flutter_flavorizr: ^2.2.1
  http_parser: ^4.0.2
  mime: ^1.0.4

flavorizr:
  flavors:
    production:
      app:
        name: "Jobs Pot"
      android:
        applicationId: "com.example.jobs_pot"
        firebase:
          config: "./android/app/google-services.json"
      ios:
        bundleId: "com.example.jobsPot"
        firebase:
          config: "./ios/Runner/GoogleService-Info.plist"

    dev:
      app:
        name: "Jobs Pot Dev"
      android:
        applicationId: "com.example.jobs_pot.dev"
        firebase:
          config: "./android/app/google-services-dev.json"
      ios:
        bundleId: "com.example.jobsPot.dev"
        firebase:
          config: "./ios/Runner/GoogleService-Info-dev.plist"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  riverpod_generator: ^2.3.5
  json_serializable: ^6.7.0
  auto_route_generator: ^7.1.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/resources/i18n/langs/
    - lib/assets/iconsPng/
    - lib/assets/imagesPng/
    - lib/assets/iconsPng/company/
    - lib/assets/iconsPng/languages/
    - lib/assets/iconsSvg/
    - lib/assets/imagesSvg/
    - lib/assets/iconsSvg/arrow/
    - lib/assets/iconsSvg/specialization/
    - lib/assets/iconsSvg/tabBar/
  fonts:
    - family: DMSans-Bold
      fonts:
        - asset: lib/resources/fonts/DMSans-Bold.ttf
    - family: DMSans-BoldItalic
      fonts:
        - asset: lib/resources/fonts/DMSans-BoldItalic.ttf
          style: italic
    - family: DMSans-Italic
      fonts:
        - asset: lib/resources/fonts/DMSans-Italic.ttf
          style: italic
    - family: DMSans-Medium
      fonts:
        - asset: lib/resources/fonts/DMSans-Medium.ttf
    - family: DMSans-MediumItalic
      fonts:
        - asset: lib/resources/fonts/DMSans-MediumItalic.ttf
          style: italic
    - family: DMSans-Regular
      fonts:
        - asset: lib/resources/fonts/DMSans-Regular.ttf
